server.port=5000

spring.jpa.show-sql=true
#spring.datasource.url=jdbc:h2:file:C://Temp/Matrix2
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=password
spring.datasource.url=jdbc:mysql://localhost:3306/matrix2
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=matrix2
spring.datasource.password=matrix2

spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.properties.hibernate.format_sql=true
#spring.h2.console.enabled=true
#spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.hibernate.ddl-auto=none
#spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

jwt.secret=SECRET

debug=true 
#logging.level.org=DEBUG 
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.servlet.mvc.method.annotation=DEBUG
logging.level.org.springframework.security=DEBUG
#logging.level.com=DEBUG
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG
#logging.level.web=DEBUG
logging.level.com.dca=DEBUG 
spring.mvc.log-request-details=true

spring.servlet.multipart.max-file-size=500000KB
spring.servlet.multipart.max-request-size=500000KB

enableLoggingRequestDetails=true
spring.http.log-request-details=true
matrix.file_directory=C://Temp/matrix_files

#Server=localhost\SQLEXPRESS;Database=master;Trusted_Connection=True;