package com.dca.matrix.api;

public enum ApiErrorCode
{
	NONE,
	INTERNAL_SERVER_ERROR,
	NOT_AUTHORIZED, 
	VALIDATION_ERROR,
	ENTITY_DOES_NOT_EXIST, 
	ENTITIES_ARE_NOT_IN_SAME_CASE,
	FILE_DOES_NOT_EXIST,
	ENTITY_FILE_DOES_NOT_EXIST, 
	CASE_DOES_NOT_EXIST,
	ERROR_UPLOADING_FILE, 
	ERROR_RETRIEVEING_FILE,
	DUPLICATE_PRIMARY_KEY,
	FIELD_VALIDATION_ERROR,
	USER_DOES_NOT_EXIST,
	USER_NOT_ASSIGNED_TO_CASE,
	USER_DISABLED,
	TASK_DOES_NOT_EXIST,
	ENTITY_RELATIONSHIP_DOES_NOT_EXIST,
	LINK_CHART_DOES_NOT_EXIST,
	LINK_CHART_CASE_INCORRECT,	
	INCORRECT_CASE_FOR_ENTITY,
	TIMELINE_DOES_NOT_EXIST,
	INVALID_CREDENTIALS
}
